# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy on Test Server

on:
  pull_request:
    types: [closed] # when PR closed
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      ## Build Project
    - name: Build with Gradle
      run: ./gradlew build
      # Docker Package 배포
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ secrets.TOKEN }}
        tag: |
          latest
          ${{github.sha}}
        imageName: test
    - name: Deploy on Test Server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cat ~/packageToken | sudo docker login https://docker.pkg.github.com --username always0ne  --password-stdin && sudo docker stop testserver && sudo docker rm testserver && sudo docker run -d  -p 8080:8080 --name=testserver -v /etc/localtime:/etc/localtime:ro  -e TZ=Asia/Seoul  --restart=unless-stopped docker.pkg.github.com/always0ne/springbootrestapitemplate/test:${{github.sha}}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY}}